export const QuestionActionTypes = {
  GET_QUESTIONS_REQUEST: "GET_QUESTIONS_REQUEST",
  GET_QUESTIONS_SUCCESS: "GET_QUESTIONS_SUCCESS",
  GET_QUESTIONS_FAILURE: "GET_QUESTIONS_FAILURE",
  DELETE_QUESTION_REQUEST: "DELETE_QUESTION_REQUEST",
  SELECT_QUESTION: "SELECT_QUESTION",
  UPDATE_SELECTED_QUESTION: "UPDATE_SELECTED_QUESTION",
};
